apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
  - gedtotal-signature-service-configmap.yml
  - secret-template.yaml
images:
  - name: docker.io/eurival/gedtotal-signature-service
    newTag: 0.0.1-SNAPSHOT
namespace: gedtotalap-apps
