apiVersion: v1
kind: Secret
metadata:
  name: gedtotal-signature-service-secrets
  namespace: gedtotalap-apps
type: Opaque
stringData:
  APP_SECURITY_INTERNAL_SHARED_TOKEN: "change-me"
  TSA_API_KEY: "change-me"
  ICP_CERT_PASSWORD: "change-me"
