apiVersion: v1
kind: Service
metadata:
  name: gedtotal-signature-service
  namespace: gedtotalap-apps
  labels:
    app: gedtotal-signature-service
spec:
  selector:
    app: gedtotal-signature-service
  ports:
    - name: http
      port: 8091
      targetPort: 8091
  type: ClusterIP
